[build-system]
requires = ["setuptools", "wheel", "pytest-runner"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore",
    "default:::comitup",
    "default:::web",
    "default:::cli"
]

asyncio_default_fixture_loop_scope = "function"
