#!/bin/bash

declare -a Paths=("/etc/comitup.conf" \
       "/usr/share/dbus-1/system.d/comitup-dbus.conf" \
       "/lib/systemd/system/comitup.service" \
       "/usr/sbin/comitup" \
       "/var/lib/comitup" \
       "/usr/lib/python3/dist-packages/comitup/comitup.py"\
       "/usr/lib/python3/dist-packages/comitup_cli/comitupcli.py"\
       "/usr/lib/python3/dist-packages/comitup_web/comitupweb.py")

retval=0
for path in ${Paths[@]}; do
    if [ ! -e $path ]; then
        echo "Not found - $path"
        retval=1
    fi
done

exit $retval
