#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'comitup==1.3','console_scripts','comitup-cli'
__requires__ = 'comitup==1.3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('comitup==1.3', 'console_scripts', 'comitup-cli')()
    )
