module.exports = async (browser, { username, password }) => {
  // most of this code is generated by a recording chrome extension https://chrome.google.com/webstore/detail/puppeteer-recorder/djeegiggegleadkkbgopoonhjimgehda?hl=en
  // then edited slightly to remove session cookies on initial login, and pull out the actual username and password into the function parameters
  const page = await browser.newPage();
  const navigationPromise = page.waitForNavigation();

  await page.goto("https://esoe.qut.edu.au");
  console.log("setting viewport");
  await page.setViewport({ width: 1853, height: 981 });

  await navigationPromise;
  await navigationPromise;

  console.log("inserting username");
  await page.waitForSelector("#loginSuccessful #username");
  await page.click("#loginSuccessful #username");
  await page.type("#loginSuccessful #username", username);

  console.log("inserting password");
  await page.waitForSelector("#loginSuccessful #password");
  await page.click("#loginSuccessful #password");
  await page.type("#loginSuccessful #password", password);

  console.log("Clicking 'remember me'");
  await page.waitForSelector(
    "div > #loginSuccessful > .form-group-container > .checkbox > label"
  );
  await page.click(
    "div > #loginSuccessful > .form-group-container > .checkbox > label"
  );

  console.log("attempting login");
  await page.waitForSelector("#login-box-wrapper #kc-login");
  await page.click("#login-box-wrapper #kc-login");

  await navigationPromise;

  await navigationPromise;
};
